version: "3"
services: 
    node-app:
        build: 
            context: .
            args: 
                NODE_ENV: development
        volumes: 
            - ./:/app
            - /app/node_modules
        environment: 
            - NODE_ENV=development
            - MONGO_USER=user
            - MONGO_PASSWORD=secret
            - SESSION_SECRET=secret
        command: npm run dev
    mongo-db:        
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=user
            - MONGO_INITDB_ROOT_PASSWORD=secret
    